# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0028_auto_20180126_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adj',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='adp',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='aux',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='cconj',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='det',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='intj',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='n_parent', to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='numeral',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='part',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='pron',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='punct',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='sconj',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bibliography.Text'),
        ),
        migrations.AlterField(
            model_name='sym',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='token',
            name='selected_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='selected_tag', to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='token',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Sentence'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='v_parent', to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='x',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tokenization.Word'),
        ),
    ]
