# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiction',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bibliography.Text'),
        ),
        migrations.AlterField(
            model_name='press',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bibliography.Text'),
        ),
    ]
