# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0002_auto_20190210_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('bibliography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliography.Bibliography')),
                ('text_publication_date', models.CharField(max_length=15)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('sphere', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bibliography.Text')),
            ],
            bases=('bibliography.bibliography',),
        ),
    ]
